micronaut:
  application:
    name: tipocambio
jackson:
  serialization:
    writeDatesAsTimestamps: false
bccr:
  url: ${BCCR_URL:`https://gee.bccr.fi.cr/Indicadores/Suscripciones/WS/wsindicadoreseconomicos.asmx`}
  token: ${BCCR_TOKEN:tokenvalue}
  nombre: ${BCCR_NOMBRE:username}
  correo: ${BCCR_CORREO:username@example.com}